[package]
name = "day19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-iterator = "1.2.0"
enum-map = "2.4.2"
enumset = "1.0.12"
impl_ops = "0.1.1"
rc = "0.1.1"
regex = "1.7.0"
