[package]
name = "day{{aoc_day}}"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.21"

[build-dependencies]
aoc-cli = "0.12.0"
